### ISSUE TITLE
cli send命令存在不兼容问题

### ISSUE THREAD

**Issue by harrylee2015** [33cn/plugin#230]
**Describe the bug**

**To Reproduce**
1. 比如配置平行共识节点时，无法用send 一条龙串起
```bash
harry@harry-VirtualBox:~/parachain$ ./chain33-cli  send  config  config_tx -o add -k paracross-nodes-user.p.guodun.  -v  14KEKbYtKKQm4wMthSK9J4La4nAiidGozt   -k 14KEKbYtKKQm4wMthSK9J4La4nAiidGozt
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/dapp/commands.OneStepSend(0xc0000c2000, 0xc, 0xc)
	/home/harry/gopath/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/dapp/commands/send.go:36 +0x1451
github.com/33cn/plugin/vendor/github.com/33cn/chain33/util/cli.Run(0x14c1669, 0x15, 0x0, 0x0)
	/home/harry/gopath/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/util/cli/cli.go:103 +0x2cf
main.main()
	/home/harry/gopath/src/github.com/33cn/plugin/cli/main.go:21 +0x81

```
之前在在用其他模块命令时也会存在不兼容问题，无法使用send命令，实现create,sign,send一条龙服务

**Comment by vipwzw** [comment]
@linj-disanbo  你来处理吧

**Comment by harrylee2015** [comment]
下面这个用send 生成的tx 是有问题的，查找不到交易
```bash
harry@harry-VirtualBox:~/chain33Test$ ./chain33-cli  send token send_exec -a 1000 -e paracross -s NAS  -k  16ReZHzMCGtPt8B7XbnZQ2jeXsPG9wEufh
0xf1b975790088ac897580e43228ffd695dec96a0f924146830f501a3c97637af9
harry@harry-VirtualBox:~/chain33Test$ ./chain33-cli tx query_hash -s 0xf1b975790088ac897580e43228ffd695dec96a0f924146830f501a3c97637af9  --rpc_laddr http://localhost:8801
{
    "txs": [
        null
    ]
}
```

**Comment by linj-disanbo** [comment]
已经修改，合并
