### ISSUE TITLE
ut wallet sentx 超时未恢复

### ISSUE THREAD

**Issue by mdj33** [33cn/plugin#387]
goroutine 42 [chan receive, 9 minutes]:
github.com/33cn/plugin/vendor/github.com/33cn/chain33/queue.(*client).WaitTimeout(0xc4237c4060, 0xc427c3cb80, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/home/pony/go/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/queue/client.go:121 +0xe7
github.com/33cn/plugin/vendor/github.com/33cn/chain33/client.(*QueueProtocol).query(0xc421cc3c60, 0x1cc8b70, 0x7, 0x1, 0x1c9a8a0, 0xc427c3e900, 0x47, 0x47, 0x1)
	/home/pony/go/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/client/queueprotocol.go:71 +0x215
github.com/33cn/plugin/vendor/github.com/33cn/chain33/client.(*QueueProtocol).SendTx(0xc421cc3c60, 0xc427c3e900, 0xc4276ac3c0, 0xc427c3ace0, 0xc427c3acc0)
	/home/pony/go/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/client/queueprotocol.go:112 +0x91
github.com/33cn/plugin/vendor/github.com/33cn/chain33/wallet.(*Wallet).sendTx(0xc423b74000, 0xc427c3e900, 0x2a85cc0, 0xc427e2bf80, 0x0)
	/home/pony/go/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/wallet/sendtx.go:137 +0x7e
github.com/33cn/plugin/vendor/github.com/33cn/chain33/wallet.(*Wallet).sendTransaction(0xc423b74000, 0x2a7b6c0, 0xc427c3cb40, 0xc4293db028, 0x6, 0x8, 0x2a85cc0, 0xc427e2bf80, 0xc4220803f0, 0x22, ...)
	/home/pony/go/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/wallet/sendtx.go:122 +0x367
github.com/33cn/plugin/vendor/github.com/33cn/chain33/wallet.(*Wallet).SendTransaction(0xc423b74000, 0x2a7b6c0, 0xc427c3cb40, 0xc4293db028, 0x6, 0x8, 0x2a85cc0, 0xc427e2bf80, 0x0, 0x0, ...)
	/home/pony/go/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/wallet/sendtx.go:107 +0xe4
github.com/33cn/plugin/plugin/dapp/ticket/wallet.(*ticketPolicy).openticket(0xc421e0d0e0, 0xc425a2e2d0, 0x22, 0xc425a2e2d0, 0x22, 0x2a85cc0, 0xc427e2bf80, 0x1, 0x6e90ab, 0xc421e132b8, ...)
	/home/pony/go/src/github.com/33cn/plugin/plugin/dapp/ticket/wallet/ticket.go:594 +0xb8d
github.com/33cn/plugin/plugin/dapp/ticket/wallet.(*ticketPolicy).buyTicketOne(0xc421e0d0e0, 0x27, 0x2a85cc0, 0xc427e2bf80, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
	/home/pony/go/src/github.com/33cn/plugin/plugin/dapp/ticket/wallet/ticket.go:637 +0x53e
github.com/33cn/plugin/plugin/dapp/ticket/wallet.(*ticketPolicy).buyTicket(0xc421e0d0e0, 0x27, 0xb, 0xc4275b9a00, 0x2, 0x2, 0x2, 0x1)
	/home/pony/go/src/github.com/33cn/plugin/plugin/dapp/ticket/wallet/ticket.go:654 +0x1b2
github.com/33cn/plugin/plugin/dapp/ticket/wallet.(*ticketPolicy).autoMining(0xc421e0d0e0)

**Comment by mdj33** [comment]
fixed by yuanxingqian
